name: xenium
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - arpack=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2026.2.25
  - glpk=5.0
  - gmp=6.3.0
  - igraph=1.0.1
  - ld_impl_linux-64=2.44
  - leidenalg=0.11.0
  - libblas=3.11.0
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblapack=3.11.0
  - libleidenalg=0.12.0
  - liblzma=5.8.2
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.15.2
  - libxml2-16=2.15.2
  - libxml2-devel=2.15.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=25.0
  - pip=26.0.1
  - pthread-stubs=0.3
  - python=3.11.15
  - python-igraph=1.0.0
  - python_abi=3.11
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.2
  - texttable=1.7.0
  - tk=8.6.15
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - zlib=1.3.1
  - pip:
      - aiobotocore==3.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - anndata==0.12.10
      - annotated-types==0.7.0
      - annsel==0.1.2
      - array-api-compat==1.14.0
      - asciitree==0.3.3
      - asttokens==3.0.1
      - attrs==25.4.0
      - botocore==1.42.61
      - cellpose==4.0.9
      - certifi==2026.2.25
      - charset-normalizer==3.4.6
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorcet==3.1.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.4.3
      - cycler==0.12.1
      - dask==2026.1.1
      - dask-image==2025.11.0
      - datashader==0.18.2
      - debugpy==1.8.20
      - decorator==5.2.1
      - deprecated==1.3.1
      - distributed==2026.1.1
      - docrep==0.3.2
      - donfig==0.8.1.post1
      - et-xmlfile==2.0.0
      - executing==2.2.1
      - fast-array-utils==1.3.1
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - fastremap==1.18.0
      - filelock==3.25.2
      - fill-voids==2.1.1
      - flowio==1.4.0
      - fonttools==4.62.1
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - geopandas==1.1.3
      - google-crc32c==1.8.0
      - gseapy==1.2.1
      - h5py==3.16.0
      - idna==3.11
      - imagecodecs==2025.11.11
      - imageio==2.37.3
      - importlib-metadata==8.7.1
      - inflect==7.5.0
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.1.0
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.5.0
      - lazy-loader==0.5
      - legacy-api-wrap==1.5
      - llvmlite==0.46.0
      - locket==1.0.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - matplotlib-scalebar==0.9.0
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.3
      - narwhals==2.18.0
      - natsort==8.4.0
      - nbclient==0.10.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numba==0.64.0
      - numcodecs==0.15.1
      - numpy==2.4.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - ome-types==0.6.3
      - ome-zarr==0.14.0
      - omnipath==1.0.12
      - opencv-python-headless==4.13.0.92
      - openpyxl==3.1.5
      - pandas==2.3.3
      - param==2.3.2
      - parso==0.8.6
      - partd==1.4.2
      - pathlib-abc==0.5.2
      - patsy==1.0.2
      - pexpect==4.9.0
      - pillow==12.1.1
      - pims==0.7
      - platformdirs==4.9.4
      - plotly==6.6.0
      - pooch==1.9.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==23.0.1
      - pyct==0.6.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.11.1
      - pygments==2.19.2
      - pynndescent==0.6.0
      - pyogrio==0.12.1
      - pyparsing==3.3.2
      - pyproj==3.7.2
      - python-dateutil==2.9.0.post0
      - pytz==2026.1.post1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rangehttpserver==1.4.0
      - readfcs==2.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.3.3
      - roifile==2026.2.10
      - rpds-py==0.30.0
      - s3fs==2026.2.0
      - scanpy==1.11.5
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.17.1
      - seaborn==0.13.2
      - segment-anything==1.0
      - session-info==1.0.1
      - session-info2==0.4
      - shapely==2.1.2
      - six==1.17.0
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - spatial-image==1.2.3
      - spatialdata==0.7.2
      - spatialdata-io==0.6.0
      - spatialdata-plot==0.2.14
      - squidpy==1.8.1
      - stack-data==0.6.3
      - statsmodels==0.14.6
      - stdlib-list==0.12.0
      - sympy==1.14.0
      - tblib==3.2.2
      - threadpoolctl==3.6.0
      - tifffile==2026.3.3
      - toolz==1.1.0
      - torch==2.10.0
      - torchvision==0.25.0
      - tornado==6.5.5
      - tqdm==4.67.3
      - traitlets==5.14.3
      - triton==3.6.0
      - typeguard==4.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - umap-learn==0.5.11
      - universal-pathlib==0.3.10
      - urllib3==2.6.3
      - validators==0.35.0
      - wcwidth==0.6.0
      - wrapt==2.1.2
      - xarray==2026.2.0
      - xarray-dataclass==3.0.0
      - xarray-spatial==0.5.3
      - xmltodict==1.0.4
      - xsdata==26.2
      - yarl==1.23.0
      - zarr==3.1.6
      - zict==3.0.0
      - zipp==3.23.0
