name: xenium
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - matplotlib
  - nbclient
  - nbformat
  - papermill
  - numpy
  - pandas
  - pyyaml
  - python-igraph
  - leidenalg
  - scanpy
  - session-info
  - spatialdata
  - spatialdata-io
  - spatialdata-plot
  - squidpy
