name: Stub run

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nf-core/setup-nextflow@v2
        with:
          version: '>=25.10.0'

      - name: Stub create_sdata
        run: nextflow run main.nf --step create_sdata -stub --samplesheet assets/samplesheet.csv

      - name: Stub create_follicle_sdata
        run: nextflow run main.nf --step create_follicle_sdata -stub --samplesheet assets/ci_analyze_samplesheet.csv

      - name: Stub cluster_sdata
        run: nextflow run main.nf --step cluster_sdata -stub --samplesheet assets/ci_analyze_samplesheet.csv

      - name: Stub concat_sdata
        run: nextflow run main.nf --step concat_sdata -stub --samplesheet assets/ci_analyze_samplesheet.csv

      - name: Stub downsample_sdata
        run: nextflow run main.nf --step downsample_sdata -stub --samplesheet assets/ci_analyze_samplesheet.csv --fraction 0.1

      - name: Stub downsample_xenium_region
        run: nextflow run main.nf --step downsample_xenium_region -stub --samplesheet assets/samplesheet.csv

      - name: Stub plot_follicle
        run: nextflow run main.nf --step plot_follicle -stub --samplesheet assets/ci_analyze_samplesheet.csv
