name: Stub run

on:
  pull_request:
    branches:
      - main

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nf-core/setup-nextflow@v2
        with:
          version: '>=25.10.0'

      - name: Stub create.nf
        run: nextflow run create.nf -stub --samplesheet assets/samplesheet.csv

      - name: Stub analyze.nf
        run: nextflow run analyze.nf -stub --samplesheet assets/ci_analyze_samplesheet.csv --analyze plot_follicle
